name: Expressions implementation
on: push
env:
    appName: CounterApp
    
jobs:
  build_job:
    runs-on:windows-latest
    steps:
      - name: Execute command
        run: echo "Build automation for application: ${{env.appName}}"
      - name: exceuting build step
        id: exec
        run:exit1
      - name: Check if the previous step is success or failure
        run: echo "Running on failure"
        if: ${{failre() && steps.exec.conclusion == 'failure' }}
